### ISSUE TITLE
Ruby China 过来的，给几点建议

### ISSUE THREAD

**Issue by 1c7** [zhangzitao/airtry#1]
1. README 要大大改进，开头就放一个可访问地址，做 DEMO 用途
2. 写清楚是什么，解决什么问题。
2. 写清楚技术栈。
3. 写一个 developer guide，给其他想加入的程序员明白怎么 clone 下来然后跑起来
3. 如果打算长久做下去，可以写个 roadmap 说清楚接下来要做什么，其他人看了会决定有没有兴趣一起做。

基本就这样，下次再想到什么在补。
祝项目成功。不管是练手也好或者什么其他目的。

**Comment by zhangzitao** [comment]
中肯的建议，已加入readme，非常感谢~
